FROM ubuntu:16.04

MAINTAINER <<vishwak.N.D>>
RUN apt-get update -y && \
   apt-get install -y python-pip python-dev
COPY ./requirements.txt /app/requirements.txt
COPY ./recordService.py /app/recordService.py
WORKDIR /app
RUN pip install -r requirements.txt
RUN pip install flask_cors
COPY . /app
ENTRYPOINT [ "python" ]
CMD [ "service.py" ]